apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  type: NodePort
  selector:
    app: recommendation-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
